/**
 * This code was generated by Builder.io.
 */
import React from "react";

const BrandVoice: React.FC = () => {
  return (
    <>
      <h3 className="self-start mt-4 ml-3.5 text-sm font-medium leading-none text-slate-400 max-md:ml-2.5">
        Brand voice
      </h3>
      <div className="flex flex-col py-3.5 mt-1.5 max-w-full rounded-xl bg-slate-500 bg-opacity-30 w-[233px]">
        <div className="flex z-10 gap-5 justify-between mr-2.5 max-md:ml-2.5">
          <div className="flex flex-col">
            <div className="self-start text-xs text-center text-white">
              Professional
            </div>
            <div className="flex mt-1.5">
              <div className="flex flex-col my-auto text-xs text-center text-white whitespace-nowrap max-md:-mr-1">
                <div className="flex shrink-0 rounded bg-[linear-gradient(264deg,#0F2283_3.87%,#0075FF_103.97%)] h-[5px] w-[105px]" />
                <div className="self-start mt-4">Descriptive</div>
                <div className="flex shrink-0 mt-2 rounded bg-[linear-gradient(264deg,#0F2283_3.87%,#0075FF_103.97%)] h-[5px] w-[105px]" />
              </div>
              <div className="flex flex-col">
                <div className="flex shrink-0 h-2.5 bg-white rounded-xl" />
                <div className="flex shrink-0 mt-8 h-2.5 bg-white rounded-xl" />
              </div>
            </div>
          </div>
          <div className="flex flex-col self-start text-xs text-center text-white whitespace-nowrap">
            <div className="self-end">Fun</div>
            <div className="mt-7">Abstract</div>
          </div>
        </div>
      </div>
    </>
  );
};

export default BrandVoice;
