/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Logo: React.FC = () => {
  return (
    <div className="flex gap-2 max-w-full w-[214px]">
      <div className="flex items-start shadow-[0px_1px_3px_rgba(16,24,40,0.1)]">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/14b94b5e200671b87d9a66fba38c6ea363188d880c98ba2119321a6b6d655f8a?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
          alt="Originality Engine Logo"
          className="object-contain w-8 rounded-lg aspect-square"
        />
      </div>
      <div className="grow shrink my-auto text-sm font-medium leading-none text-center tracking-[2.35px] w-[169px]">
        ORIGINALITY ENGINE
      </div>
    </div>
  );
};

export default Logo;
