/**
 * This code was generated by Builder.io.
 */
import React from "react";

const MainContent: React.FC = () => {
  return (
    <main className="flex flex-col ml-5 w-[84%] max-md:ml-0 max-md:w-full">
      <div className="flex relative flex-col items-center px-20 pt-96 pb-28 mt-32 text-white min-h-[920px] max-md:px-5 max-md:py-24 max-md:mt-10 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/53ceb5a8d1a436489908535570e2dd94cf1fb71571d19ee5075460ab69291dc2?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
          alt=""
          className="object-cover absolute inset-0 size-full"
        />
        <div className="flex relative flex-col max-w-full w-[693px]">
          <h1 className="self-center text-4xl font-medium leading-none">
            Assessing...
          </h1>
          <p className="mt-72 text-2xl text-center max-md:mt-10 max-md:max-w-full">
            Tip: If you run out of ideas, enrich your prompts using Olly, our
            built-in prompt generator
          </p>
        </div>
      </div>
    </main>
  );
};

export default MainContent;
