/**
 * This code was generated by Builder.io.
 */
import React from "react";

const PromptInput: React.FC = () => {
  return (
    <>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/45de8afa172b1fd9b2b1c14bd7a41bb6edd86e176a75346d2a61943516da7ec4?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
        alt=""
        className="object-contain mt-6 max-w-full aspect-[250] w-[233px]"
      />
      <div className="flex gap-3 mt-4 max-w-full text-sm leading-5 rounded-xl bg-slate-500 bg-opacity-30 text-neutral-400 w-[233px]">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/255bd94cd952ee82c411995c91635eaa4d27f54c5dae901ce21dbcc6a5bbb539?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
          alt=""
          className="object-contain shrink-0 aspect-[1.01] backdrop-blur-[7.83458948135376px] fill-[linear-gradient(264deg,#0F2283_3.87%,#0075FF_103.97%)] w-[70px]"
        />
        <div className="my-auto">
          A buff man stands on the paradise beach...
        </div>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/f9b6b1a6-2158-44a3-b0f2-9002ddd9b919?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
        alt=""
        className="object-contain self-start py-1 mt-2.5 max-w-full rounded-md aspect-[9.26] bg-white bg-opacity-30 w-[241px]"
      />
    </>
  );
};

export default PromptInput;
