/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import PromptInput from "./PromptInput";
import BrandVoice from "./BrandVoice";
import TargetSegment from "./TargetSegment";
import OllySuggestion from "./OllySuggestion";
import RecentCampaigns from "./RecentCampaigns";

const Sidebar: React.FC = () => {
  return (
    <aside className="flex flex-col w-[16%] max-md:ml-0 max-md:w-full">
      <div className="flex relative flex-col grow items-start">
        <div className="flex flex-col items-center py-10 pl-3 w-full">
          <Logo />
          <PromptInput />
          <BrandVoice />
          <TargetSegment />
          <OllySuggestion />
          <button className="gap-2 self-stretch px-3 py-3.5 mt-3 max-w-full text-base font-medium leading-none text-center text-white whitespace-nowrap rounded-lg opacity-50 bg-[linear-gradient(264deg,#0F2283_3.87%,#0075FF_103.97%)] w-[233px]">
            Assessing...
          </button>
          <RecentCampaigns />
        </div>
      </div>
    </aside>
  );
};

export default Sidebar;
