/**
 * This code was generated by Builder.io.
 */
import React from "react";

const TargetSegment: React.FC = () => {
  return (
    <div className="flex flex-col px-2.5 mt-3 w-full text-white">
      <label htmlFor="targetSegment" className="self-start text-xs text-center">
        Target segment
      </label>
      <div className="flex overflow-hidden gap-1.5 items-center px-2 py-1.5 mt-2 text-xs font-medium leading-normal rounded-md bg-white bg-opacity-30 shadow-[0px_1px_1px_rgba(16,24,40,0.05)]">
        <input
          id="targetSegment"
          className="flex-1 shrink gap-1.5 self-stretch my-auto w-full bg-transparent border-none outline-none"
          type="text"
          value="Male, Ages 18-25, Middle Class"
          readOnly
        />
      </div>
    </div>
  );
};

export default TargetSegment;
