/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="flex flex-col items-center py-10 pl-3 w-full">
      <div className="flex gap-2 max-w-full w-[214px]">
        <div className="flex items-start shadow-[0px_1px_3px_rgba(16,24,40,0.1)]">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/feab79eda01a82cc5af49295b03cf64b34616ee2ee12e79b16818c758f3fb7cc?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
            alt="Originality Engine Logo"
            className="object-contain w-8 rounded-lg aspect-square"
          />
        </div>
        <h1 className="grow shrink my-auto text-sm font-medium leading-none text-center tracking-[2.35px] w-[169px]">
          ORIGINALITY ENGINE
        </h1>
      </div>
    </header>
  );
};

export default Header;
