/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ImageInput: React.FC = () => {
  return (
    <section className="flex flex-col items-center">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/ec62bcd74dfea8f643a7a739495b57309a1b4a99fab9b5bbf56f2cd312fdd494?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
        alt="Input image preview"
        className="object-contain mt-6 max-w-full aspect-[250] w-[233px]"
      />
      <div className="flex gap-3 mt-4 max-w-full text-sm rounded-xl bg-slate-500 bg-opacity-30 text-neutral-400 w-[233px]">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/6f48d3c602a7bb3deebafece32466585c65865870610678055d36dd01eba8cf4?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
          alt=""
          className="object-contain shrink-0 aspect-[1.01] backdrop-blur-[7.83458948135376px] fill-[linear-gradient(264deg,#0F2283_3.87%,#0075FF_103.97%)] w-[70px]"
        />
        <div className="grow shrink my-auto w-[138px]">A man on the beach</div>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/8d0fb569-de5b-47a3-81ef-b514559decc6?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
        alt="Input controls"
        className="object-contain self-start py-1 mt-2.5 max-w-full rounded-md aspect-[9.26] bg-white bg-opacity-30 w-[241px]"
      />
    </section>
  );
};

export default ImageInput;
