/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ImagePrompt: React.FC = () => {
  return (
    <h2 className="self-stretch mt-5 text-4xl font-medium leading-none text-slate-400">
      &quot;A man on the beach&quot;
    </h2>
  );
};

export default ImagePrompt;
