/**
 * This code was generated by Builder.io.
 */
import React from "react";

const MainContent: React.FC = () => {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/0d2e5e2e-da5c-451d-b2e0-2c374edff369?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
      alt="Main content visual"
      className="object-contain my-auto w-full aspect-[1.17] max-md:max-w-full"
    />
  );
};

export default MainContent;
