/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import ImageInput from "./ImageInput";
import AssessButton from "./AssessButton";
import RecentCampaigns from "./RecentCampaigns";
import Visualizer from "./Visualizer";
import ImagePrompt from "./ImagePrompt";
import PlayButton from "./PlayButton";

const OriginalityEngine: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-col bg-slate-900">
      <div className="flex relative flex-col flex-wrap gap-10 pr-20 w-full min-h-[1155px] max-md:pr-5 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/fd7b5ea76ca7d832b50420e87da223a9fd88e1142f55ae3396841578ce336f12?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
          alt=""
          className="object-cover absolute inset-0 size-full"
        />
        <main className="flex relative flex-col items-start">
          <Header />
          <ImageInput />
          <AssessButton />
          <RecentCampaigns />
        </main>
        <aside className="flex relative flex-col items-center my-auto">
          <Visualizer />
          <ImagePrompt />
          <PlayButton />
        </aside>
      </div>
    </div>
  );
};

export default OriginalityEngine;
