"use client";
/**
 * This code was generated by Builder.io.
 */
import React from "react";

const PlayButton: React.FC = () => {
  return (
    <button className="flex overflow-hidden flex-col justify-center items-center px-6 bg-blue-950 bg-opacity-40 h-[107px] mt-[610px] rounded-[73px] w-[107px] max-md:px-5 max-md:mt-10">
      <div className="flex shrink-0 w-full bg-white rounded-md h-[45px]" />
    </button>
  );
};

export default PlayButton;
