/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Visualizer: React.FC = () => {
  const bars = [22, 68, 17, 90, 46, 28, 51, 17, 68];

  return (
    <div className="flex gap-4 justify-center items-center bg-blend-overlay min-h-[102px]">
      {bars.map((height, index) => (
        <div
          key={index}
          className="flex shrink-0 self-stretch my-auto bg-white rounded-[142px] w-[11px]"
          style={{ height: `${height}px` }}
        />
      ))}
    </div>
  );
};

export default Visualizer;
