/**
 * This code was generated by Builder.io.
 */
import React from "react";

const AdRevenue: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-col pt-4 mt-4 w-full rounded-[35px]">
      <div className="flex gap-5 justify-between self-center max-w-full text-lg font-medium w-[334px]">
        <div className="leading-5 text-white">
          <span className="text-xl text-white">Estimated ad revenue</span>{" "}
          <br />
        </div>
        <div className="self-start leading-none text-slate-400">6 months</div>
      </div>
      <div className="flex relative flex-col px-5 pb-12 mt-3.5 text-3xl font-bold leading-snug text-white whitespace-nowrap aspect-[4.022] w-[374px] max-md:pr-5">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0dc627c3d63a5a99cdba5c66fb96d00e33e4d678cb858b243b4114a3f360b0f7?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
          alt=""
          className="object-cover absolute inset-0 size-full"
        />
        $30M
      </div>
    </div>
  );
};

export default AdRevenue;
