/**
 * This code was generated by Builder.io.
 */
import React from "react";

const MarketSize: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-col pt-9 rounded-[35px]">
      <div className="flex relative flex-col items-start pr-20 pb-16 pl-5 w-full aspect-[2.992] max-md:pr-5">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0cb2acb241383ae2f84376d80248773bcd053496752bcbfea8dc6aa174eccafe?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
          alt=""
          className="object-cover absolute inset-0 size-full"
        />
        <div className="relative z-10 -mt-4 text-xl font-medium leading-5 text-white">
          Total market size <br />
        </div>
        <div className="relative mt-0 text-3xl font-bold leading-snug text-white">
          $1.2B
        </div>
      </div>
    </div>
  );
};

export default MarketSize;
