/**
 * This code was generated by Builder.io.
 */
import React, { useContext } from "react";
import { buildStyles, CircularProgressbar } from 'react-circular-progressbar';
import 'react-circular-progressbar/dist/styles.css';
import { OriginalityEngineContext } from "../../components/OriginalityEngine2/OriginalityEngine"

const OriginalityScore: React.FC = () => {
  const adResponse = useContext(OriginalityEngineContext);
  return (
    <div className="flex flex-col w-[22%] max-md:ml-0 max-md:w-full">
      <div className="flex overflow-hidden flex-col px-3.5 pt-7 text-lg font-bold leading-snug text-white rounded-3xl max-md:mt-5">
        <h3 className="self-start ml-3 max-md:ml-2.5">Originality Score</h3>
        <div className="flex justify-center w-1/2 mt-10">
          <CircularProgressbar styles={buildStyles({ textColor: "#ffffff" })} value={adResponse?.overallScore!} text={`${adResponse?.overallScore}%`} />
        </div>
      </div>
    </div>
  );
};

export default OriginalityScore;
