/**
 * This code was generated by Builder.io.
 */
import React from "react";

const OriginalityScore: React.FC = () => {
  return (
    <div className="flex flex-col w-[22%] max-md:ml-0 max-md:w-full">
      <div className="flex overflow-hidden flex-col px-3.5 pt-7 text-lg font-bold leading-snug text-white rounded-3xl max-md:mt-5">
        <h3 className="self-start ml-3 max-md:ml-2.5">Originality Score</h3>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/ab52f477-54c6-40c9-838b-491edbc8bfc9?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
          alt="Originality Score Graph"
          className="object-contain w-full rounded-none aspect-[1.1]"
        />
      </div>
    </div>
  );
};

export default OriginalityScore;
