/**
 * This code was generated by Builder.io.
 */
import React from "react";
import similarity from "../../../public/Similarity Large.png";
import Image from "next/image";

const Similarity: React.FC = () => {
  return (
    <div className="flex flex-col w-6/12 mt-10 max-md:ml-0 max-md:w-full">
        <Image width={1110} height={900} src={similarity.src} alt="similarity" />
    </div>
  );
};

export default Similarity;
