/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Similarity: React.FC = () => {
  return (
    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow items-start pt-7 pr-20 pb-14 pl-7 mt-2.5 rounded-3xl max-md:px-5 max-md:mt-7 max-md:max-w-full">
        <h3 className="text-lg font-bold leading-snug text-white">
          Similarity
        </h3>
        <div className="text-sm font-medium leading-none text-slate-400">
          by Topic
        </div>
        <div className="flex flex-col justify-center items-center self-center px-10 mt-2.5 rounded-full aspect-square bg-zinc-300 bg-opacity-10 w-[316px] max-md:px-5">
          <div className="flex flex-col justify-center items-center px-11 rounded-full aspect-square bg-zinc-300 bg-opacity-10 max-md:px-5">
            <div className="flex flex-col px-8 pt-14 pb-8 rounded-full bg-zinc-300 bg-opacity-10 h-[145px] w-[145px] max-md:px-5">
              <div className="text-lg font-bold leading-snug text-white">
                Your idea
              </div>
              <div className="self-center mt-3 text-sm font-medium leading-none text-slate-400">
                TODO
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Similarity;
