/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ViralityScore: React.FC = () => {
  return (
    <div className="flex flex-col ml-5 w-[27%] max-md:ml-0 max-md:w-full">
      Continuing from where we left off:
      <div className="flex overflow-hidden relative flex-col self-stretch px-8 py-16 m-auto leading-none rounded-full aspect-[0.936] bg-[linear-gradient(180deg,#05CD99_0%,rgba(5,205,153,0.00_92.23%))] fill-[linear-gradient(180deg,#05CD99_0%,rgba(5,205,153,0.00_92.23%))] w-[189px] max-md:px-5 max-md:mt-10">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b05603fceb992b357afda5b05096e2d887c7d143c7856ecf304b73be97771aed?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
          alt=""
          className="object-cover absolute inset-0 size-full"
        />
        <div className="relative self-end text-5xl font-bold text-white max-md:text-4xl">
          83%
        </div>
        <div className="relative self-center mt-1.5 ml-2.5 text-sm font-medium text-slate-400">
          Virality Score
        </div>
      </div>
    </div>
  );
};

export default ViralityScore;
