"use client";
import useVoiceToText from "@/app/service/voiceToText.service";
/**
 * This code was generated by Builder.io.
 */
import AssessButton from "../OriginalityEngine2/AssessButton";
import { AdResponse } from "@/app/models/AdResponse";
import { useState } from "react";

interface InputProps {
  onClick: () => void;
  handleChange: (event: React.ChangeEvent<HTMLTextAreaElement>) => void;
  modifyIdea: (updatedIdea: string) => void;
}

const IdeaInput: React.FC<InputProps> = ({
  onClick,
  handleChange,
  modifyIdea,
}) => {
  const { transcript, startListening, stopListening, clearTranscript } = useVoiceToText({ lang: 'en-US', continuous: true });
  const [isListening, setIsListening] = useState(false);

  const listen = async () => {
    if (isListening) {
      console.log("Listening stopped...");
      stopListening();
      setTimeout(getTranscript, 250);
    } else {
      clearTranscript();
      startListening();
      console.log("Listening...");
    }
    setIsListening(!isListening); 
  }

  const getTranscript = () => {
    console.log("transcript: ", transcript);
    modifyIdea(transcript);
    onClick();
  }

  return (
    <>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/48dcedf90ef934e988e1443d604a17209391e5cfe84b047cb1d2bcdd010b6534?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
        alt=""
        className="object-contain mt-6 max-w-full aspect-[250] w-[233px]"
      />
      <div className="flex gap-3 mt-4 max-w-full text-sm leading-5 rounded-xl bg-slate-500 bg-opacity-30 text-neutral-400 w-[233px]">
        <img
          loading="lazy"
          onClick={listen}
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/e26e8724aeda6ce7088834fd5a30d12e7031cb0a6be8da4824c4f3135195c6f1?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
          alt=""
          className="object-contain shrink-0 aspect-[1.01] backdrop-blur-[7.83458948135376px] fill-[linear-gradient(264deg,#0F2283_3.87%,#0075FF_103.97%)] w-[70px]"
        />
        <div className="my-auto">
          <textarea rows={3} onChange={handleChange} className="w-full bg-transparent" placeholder="Describe your idea, target segment, goal..." />
        </div>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/8a8f54a2-8e82-40ec-be38-d781b4d86eeb?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
        alt=""
        className="object-contain self-start py-1 mt-2.5 max-w-full rounded-md aspect-[9.26] bg-white bg-opacity-30 w-[241px]"
      />
      <AssessButton onClick={onClick}/>
    </>
  );
};

export default IdeaInput;
