/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import IdeaInput from "./IdeaInput";
import RecentCampaigns from "./RecentCampaigns";
import MainContent from "./MainContent";

const OriginalityEngine: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-col bg-slate-900">
      <div className="flex relative flex-col flex-wrap gap-10 pr-20 w-full min-h-[1155px] max-md:pr-5 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/02a4eb88783081748be9b6e36fcb32371e561294d0f839a6c90f7d9c37272a7c?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
          alt=""
          className="object-cover absolute inset-0 size-full"
        />
        <div className="flex relative flex-col items-start">
          <Header />
          <RecentCampaigns />
          <MainContent />
        </div>
      </div>
    </div>
  );
};

export default OriginalityEngine;
