/**
 * This code was generated by Builder.io.
 */
import React from "react";
import OriginalityScore from "./AnalyticsComponents/OriginalityScore";
import MarketSize from "./AnalyticsComponents/MarketSize";
import AdRevenue from "./AnalyticsComponents/AdRevenue";
import TrendingHashtags from "./AnalyticsComponents/TrendingHashtags";
import ViralityScore from "./AnalyticsComponents/ViralityScore";
import Similarity from "./AnalyticsComponents/Similarity";
import InspirationalVideos from "./AnalyticsComponents/InspirationalVideos";

const AnalyticsSection: React.FC = () => {
  return (
    <section className="mt-16 mr-9 ml-5 max-md:mt-10 max-md:mr-2.5 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <OriginalityScore />
        <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
          <MarketSize />
          <AdRevenue />
        </div>
        <div className="flex flex-col ml-5 w-[53%] max-md:ml-0 max-md:w-full">
          <div className="overflow-hidden grow px-11 pb-8 mt-2 rounded-3xl max-md:px-5 max-md:mt-7 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col">
              <TrendingHashtags />
              <ViralityScore />
            </div>
          </div>
        </div>
      </div>
      <div className="mt-1.5 mr-6 ml-5 max-md:mr-2.5 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <Similarity />
          <InspirationalVideos />
        </div>
      </div>
    </section>
  );
};

export default AnalyticsSection;
