/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="mt-16 mr-9 ml-5 max-md:mt-10 max-md:mr-2.5 max-md:max-w-full">
      {/* Footer content */}
    </footer>
  );
};

export default Footer;
