/**
 * This code was generated by Builder.io.
 */
import React, { useContext } from "react";
import { OriginalityEngineContext } from "../components/OriginalityEngine2/OriginalityEngine";

const Header: React.FC = () => {
  const adResponse = useContext(OriginalityEngineContext);
  return (
    <header className="flex gap-5 justify-between mr-7 w-full max-w-[1594px] max-md:mr-2.5 max-md:max-w-full">
      <div className="flex flex-wrap flex-auto gap-9 px-4 py-4 rounded-xl shadow-[0px_4px_6px_rgba(0,0,0,0.02)]">
        <h1 className="text-3xl font-bold text-center text-white">v7</h1>
        <p className="flex-auto text-sm leading-5 text-zinc-300 max-md:max-w-full">
          {adResponse?.prompt}
        </p>
      </div>
      <div className="flex my-auto text-xl whitespace-nowrap text-slate-500">
        <div className="flex overflow-hidden gap-1.5 items-center h-[25px]">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/bd1991ab27b30f0f5e3e527416fcc49f35a03feaad8c601788a62f6dcf166de4?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto aspect-square w-[19px]"
          />
          <span className="self-stretch my-auto">angelique@pepsi.co</span>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/6a40986c3be7f399b7977d2cc723347c8345f2b98c285d81232565e2e9350942?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
          alt=""
          className="object-contain shrink-0 my-auto aspect-[1.69] w-[22px]"
        />
      </div>
    </header>
  );
};

export default Header;
