/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HistorySection: React.FC = () => {
  return (
    <section className="flex flex-wrap gap-2.5 items-end mt-4">
      <div className="flex flex-col self-stretch">
        <div className="flex gap-2.5 self-start whitespace-nowrap">
          <h2 className="grow text-lg font-bold leading-snug text-white">
            History
          </h2>
          <button className="flex gap-1.5 px-2 py-1 my-auto text-sm text-center text-white rounded-xl bg-white bg-opacity-20">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/930e178622daa5fe251af64678f5170f8c9f1af408154f3dfb35c5bbfe46a803?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
              alt=""
              className="object-contain shrink-0 self-start w-4 rounded-sm aspect-[1.14]"
            />
            <span>Favorites</span>
          </button>
        </div>
        {/* History items */}
      </div>
    </section>
  );
};

export default HistorySection;
