/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import HistorySection from "./HistorySection";
import AnalyticsSection from "./AnalyticsSection";


const MainContent: React.FC = () => {
  return (
    <main className="flex relative flex-col ml-5 w-[84%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col mt-6 w-full max-md:max-w-full">
        <Header />
        <HistorySection />
        <AnalyticsSection />
      </div>
    </main>
  );
};

export default MainContent;
