/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Sidebar from "./Sidebar";
import MainContent from "./MainContent";
import Footer from "./Footer";

const MyComponent: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-col bg-slate-900">
      <div className="w-full max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <Sidebar />
          <MainContent />
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default MyComponent;
