/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Sidebar: React.FC = () => {
  return (
    <aside className="flex flex-col w-[16%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow items-start">
        <div className="flex flex-col items-start py-10 pl-6 w-full max-md:pl-5">
          <div className="flex gap-2 self-center max-w-full w-[214px]">
            <div className="flex items-start shadow-[0px_1px_3px_rgba(16,24,40,0.1)]">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/262fad9da452a913baf7049fe364cb8d1021f178b3dbafe28241702ff691500e?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
                alt="Logo"
                className="object-contain w-8 rounded-lg aspect-square"
              />
            </div>
            <div className="grow shrink my-auto text-sm font-medium leading-none text-center tracking-[2.35px] w-[169px]">
              ORIGINALITY ENGINE
            </div>
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/9685e6ab6f81760251ecf6f99f93dbce39fa66a3417cc1dbed1947cafa3ca4da?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
            alt=""
            className="object-contain mt-6 max-w-full aspect-[250] w-[233px]"
          />
          <form className="flex gap-3 mt-4 text-sm leading-5 rounded-xl bg-slate-500 bg-opacity-30 text-neutral-400">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b5aa998afee7b7322c524b19a099bfb8169b6963c34ab8458e70729944b3762?placeholderIfAbsent=true&apiKey=3502b91ecd184de6be2f646c5a302933"
              alt=""
              className="object-contain shrink-0 aspect-[1.01] backdrop-blur-[7.83458948135376px] fill-[linear-gradient(264deg,#0F2283_3.87%,#0075FF_103.97%)] w-[70px]"
            />
            <label htmlFor="ideaInput" className="sr-only">
              Describe your idea, target segment, goal...
            </label>
            <input
              id="ideaInput"
              type="text"
              placeholder="Describe your idea, target segment, goal..."
              className="bg-transparent border-none outline-none text-neutral-400 w-full"
            />
          </form>
          {/* Rest of the sidebar content */}
        </div>
      </div>
    </aside>
  );
};

export default Sidebar;
